# Generated by Django 5.1.2 on 2024-12-02 16:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuego',
            name='categoria',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='genero',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='plataforma',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
